### ISSUE TITLE
Error: "can’t multiply sequence by non-int of type “float”"

### ISSUE THREAD

**Issue by christopherd-pdx** [Phius-ResearchComittee/REVIVE#21]
In REVIVIEcalc v24.2, Simulation tab, when hitting Simulate button, I am getting an error:
**can’t multiply sequence by non-int of type “float"**
This is occurring on both Mac and Windows versions of REVIVEcalc (Sonoma 14.7 and Windows 11).
Output folder structure is created, but no results are present after error.
(This happened during an attempt to basically replicate the steps in the tutorial videos.)

**Comment by christopherd-pdx** [comment]
Additional info from the terminal window (on the Mac):
WARNING: Could not locate all outputs from resilience simulation.
WARNING: Could not locate all outputs from resilience simulation.
WARNING: Could not locate all outputs from annual simulation.
WARNING: Could not locate all outputs from annual simulation.
Process Process-6:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 315, in _bootstrap
  File "multiprocessing/process.py", line 108, in run
  File "simulate.py", line 173, in parallel_simulate
  File "simulate.py", line 210, in simulate_with_gui_communication
  File "simulate.py", line 1320, in collect_all_results
  File "pandas/core/reshape/concat.py", line 382, in concat
  File "pandas/core/reshape/concat.py", line 445, in __init__
  File "pandas/core/reshape/concat.py", line 507, in _clean_keys_and_objs
ValueError: No objects to concatenate

**Comment by amitche8** [comment]
I believe this is fixed in the new version, v24.2.1 - check back by EOD 12/4/24
